### ISSUE TITLE
Suggesting Code Change

### ISSUE THREAD

**Issue by DonBaronFactory** [apptality/ATAppUpdater#1]
The current implementation just checks whether the currentVersion is different than the latestVersion with a String comparison:

if (![latestVersion isEqualToString:currentVersion])

This causes development versions to constantly trigger the notification. I suggest the following amendment in order to check whether the latestVersion is greater than the currentVersion based on a float. This way you make sure the development version doesn't trigger the notification:

if([latestVersion floatValue]>[currentVersion floatValue])

Or add a parameter which allows to choose the type of comparison, i.e. string vs float...

**Comment by djoulz22** [comment]
Another suggest (from this post: http://stackoverflow.com/questions/1978456/compare-version-numbers-in-objective-c) : 

if ([latestVersion compare:currentVersion options:NSNumericSearch] == NSOrderedDescending)

Now "1" < "1.0" < "1.0.0" < "1.0.5"

Else your code is great! Thanks for your help ;-)

**Comment by emotality** [comment]
Thanks for this! I did the equalToString to avoid djoulz22's issue above, and it will still work as you can only upload a version number greater than the current version. But this also creates another issue mentioned in Issue #2 where Apple Review Team might pick it up and reject the application. So I will go with the suggested edits, thank you guys! ;)

**Comment by emotality** [comment]
Fixed, thanks @djoulz22 and @cre8it 

(https://github.com/emotality/ATAppUpdater/commit/45285efe559bd62bc9108d762aaced4084180a30)
