### ISSUE TITLE
Test Flight Support

### ISSUE THREAD

**Issue by novinfard** [apptality/ATAppUpdater#13]
Hello,

Does your class support "Test Flight" ?

**Comment by emotality** [comment]
Short answer: 

I doubt, as the project version needs to be lower than appstore version.

Long answer: 

This only compares the current project version (Info.plist) and live appstore version. So if there is no app on the appstore yet, you can't test it. But it really is just a matter of drag and drop as it uses the bundle info from Info.plist to compare the two version numbers on its own, you just insert one line of code. If you do have an app on the appstore, you can simply change your bundle version to 0.1 and run the app, then change it back to the newer version number. If you don't have anything on appstore, you can take one of my bundle identifiers and test on simulator.

But trust me it will work, if it doesn't I'm sure one of these 150+ people would've created an issue. ;)

Hope this answered your question?
