### ISSUE TITLE
Update check over HTTP

### ISSUE THREAD

**Issue by luander** [apptality/ATAppUpdater#14]
Hello!
The following line from **ATAppUpdater.m** is making an **HTTP** request. An attacker listening in the middle of the connection could change the results returned from the server, such as setting a malicious **trackViewUrl** and fool the app with a fake update link.
`NSURL *lookupURL = [NSURL URLWithString:[NSString stringWithFormat:@"http://itunes.apple.com/lookup?bundleId=%@", bundleIdentifier]];`

Don't you think it makes more sense to use **HTTPS**?

**Comment by emotality** [comment]
Well sure :) rather safe than sorry. Thanks I'll update this with the requested delegate functions the others asked for.

**Comment by luander** [comment]
Thank you for the quick response. 
Please let me know if I can help you in any issue.

**Comment by emotality** [comment]
Sorry for long wait guys, been super busy with full-time work and other personal projects. The above is fixed with commit dc16fe76ba81be6372323c7b24625559c6d3f9b3

Thanks for reporting issues!
