### ISSUE TITLE
Alert dismiss and not Update the App

### ISSUE THREAD

**Issue by appscarvajal** [apptality/ATAppUpdater#15]
When I open the App, the alert appears with force and carry to AppStore, but if I come back without update the App, the Alert don´t appear again. This occurs in Cordova App.

**Comment by emotality** [comment]
It depends in what delegate method you put it in. If you put it in didBecomeActive it will show every time you go into the app. But if you put it in didFinishLaunchingWithOptions it will only load the first time you load the app, you would need to exit and close the app (slide up) before it will happen again.
