### ISSUE TITLE
Can't set title or buttons' name in swift 

### ISSUE THREAD

**Issue by onepiece502** [apptality/ATAppUpdater#16]
```
        var updater = ATAppUpdater.sharedUpdater()
        updater.alertTitle = "aaa"
        updater.alertUpdateButtonTitle = "b"
        updater.alertCancelButtonTitle = "cc"
```

> error: " updater is immutable"

I change my code to below:

`var updater = ATAppUpdater.sharedUpdater() as! ATAppUpdater`

after setting the properties the alert view remains little things that not set by code.

**Comment by emotality** [comment]
Hi, first off, I didn't write it in swift, may I ask where you got it?

**Comment by emotality** [comment]
For now, I can't really help you with swift. But to think what the possible issues there can be I assume there's something wrong with how you set the properties and the instance method?

Can you maybe fork the project then push your code for us to see? Maybe I or anyone else can help, if not you can reference it from StackOverflow for help, sorry!

**Comment by emotality** [comment]
Re-open when you are still struggling. And please provide some code with the issue as there is no swift version for now. Thanks! 👍
