### ISSUE TITLE
alertMessage the custom value  is error

### ISSUE THREAD

**Issue by mengday** [apptality/ATAppUpdater#18]
updater.alertMessage = NSLocalizedString(@"最新版本位为：%@ ", @"Alert Message");
error ：Could not find a storyboard named 'Main' in bundle NSBundle

**Comment by emotality** [comment]
`Could not find a storyboard named 'Main' in bundle NSBundle` has nothing to do with ATAppUpdater.

Just create/add a `Main.storyboard` file to your project..
