### ISSUE TITLE
Be very careful when using it.

### ISSUE THREAD

**Issue by ZebedeeTR** [apptality/ATAppUpdater#2]
There is a very useful control.
But you have to be very careful when using it.
Apple rejected my application because of this control.

I received message that below from Apple.

10.6 Details  

Your app includes an update button or alerts the user to update the app. To avoid user confusion, app version updates must utilize the iOS built-in update mechanism. 

We’ve attached screenshot(s) for your reference.

Next Steps

Please remove the update feature from your app. To distribute a new version of your app, upload the new app binary version into the same iTunes Connect record you created for the app’s previous version. Updated versions keep the same Apple ID, iTunes Connect ID (SKU), and bundle ID as the original version, and are available free to customers who purchased a previous version.

**Comment by emotality** [comment]
Hi! I think if I do the update the other suggested in the other issue, this might not be the problem, will have to see. Thanks for the heads up!
