### ISSUE TITLE
Crashed when tap Update

### ISSUE THREAD

**Issue by Djangovn** [apptality/ATAppUpdater#22]
Hi, 

I just found your project. This's exactly what I want. But when I added it to my code, my app crashed when I tap on "Update". Here's the log:
`[[UIApplication sharedApplication] openURL:[NSURL URLWithString:appStoreURL]]; // Error: Thread: 1: EXC_BAD_ACCESS (code=1, address=0x347426fd46e7469)`

Please note my app not yet published so I replace 'lookupURL' in ATAppUpdater.m with another bundle ID.

Thanks and best regards,

Django

**Comment by Djangovn** [comment]
I change NSString appStoreURL to appStoreURL2 it not crash anymore but nothing happened

**Comment by emotality** [comment]
Hi, 

Did you run this on a real device or sim? :)

**Comment by Djangovn** [comment]
Hi,

I tried with real device

**Comment by emotality** [comment]
> Please note my app not yet published so I replace 'lookupURL' in ATAppUpdater.m with another bundle ID.

You shouldn't change any URL, in fact, you shouldn't change anything at all. You should just have your own bundle ID in your info plist / project settings.

If the example project works with the Telegram bundle ID `(ph.telegra.Telegraph)` on a real device, then it should work for you with your own bundle ID. :)

Does the example project work for you?
