### ISSUE TITLE
关于更新 路径 的问题

### ISSUE THREAD

**Issue by guanqing123** [apptality/ATAppUpdater#24]
NSURL *lookupURL = [NSURL URLWithString:[NSString stringWithFormat:@"https://itunes.apple.com/lookup?bundleId=%@", bundleIdentifier]];
使用这个请求路径，目前很难返回结果。经测试，需要加上国家:
NSURL *lookupURL = [NSURL URLWithString:[NSString stringWithFormat:@"https://itunes.apple.com/lookup?bundleId=%@&country=cn", bundleIdentifier]];
请测试看看。谢谢

**Comment by emotality** [comment]
English only :)
