### ISSUE TITLE
Can't install ATAppUpdater via Carthage

### ISSUE THREAD

**Issue by ARGAMX** [apptality/ATAppUpdater#26]
Cartfile:

> github "emotality/ATAppUpdater"

Terminal:

> iMac:App-iOS-Sources user$ carthage update --platform iOS --no-use-binaries
> *** Cloning ATAppUpdater
> *** Checking out ATAppUpdater at "2.0"
> *** xcodebuild output can be found in > /var/folders/nb/9g4bcynn1bbbl93rrd7nns4h0000gn/T/carthage-xcodebuild.GXFOtL.log
> *** Skipped building ATAppUpdater due to the error:
> Dependency "ATAppUpdater" has no shared framework schemes for any of the platforms: iOS
> If you believe this to be an error, please file an issue with the maintainers at https://github.com/emotality/ATAppUpdater/issues/new

**Comment by emotality** [comment]
Hi @ARGAMX 

I haven't touched iOS in 3 years and don't event know what Carthage is. 
Maybe someone else here can help?

**Comment by ARGAMX** [comment]
> Hi @ARGAMX
> 
> I haven't touched iOS in 3 years and don't event know what Carthage is.
> Maybe someone else here can help?

Looks like pretty easy thing:

https://amerhukic.com/how-to-add-carthage-support-in-existing-cocoapod-project

https://webcache.googleusercontent.com/search?q=cache:gNv43se4RWIJ:https://amerhukic.com/how-to-add-carthage-support-in-existing-cocoapod-project

https://github.com/Carthage/Carthage#share-your-xcode-schemes
