### ISSUE TITLE
Cocoa Pod

### ISSUE THREAD

**Issue by petalvlad** [apptality/ATAppUpdater#4]
This will be really great if you wrap it into Cocoa Pod.

Thanks for great lib!

**Comment by emotality** [comment]
Thank you so much Alex! Much appreciated! :)
I will have a look into it, thanks for the idea. ;)

**Comment by emotality** [comment]
Created the Pod: 2d7c305c65c542e86ee484db3e8a46bd4d7f4f37 
CocoaDocs: http://cocoadocs.org/docsets/ATAppUpdater/1.2/ 

Thanks for the "review" :+1:  https://trello.com/c/LM6pmJdz/9-atappupdater-ios
