### ISSUE TITLE
Version compare is not correct

### ISSUE THREAD

**Issue by atrwang** [apptality/ATAppUpdater#9]
app store version is 1.4.135,  Install the 1.4.135 on iPhone

NSString *currentVersion = [bundleInfo objectForKey:@"CFBundleShortVersionString"];
// 1.4

NSString *latestVersion = [appDetails objectForKey:@"version"];
//1.4.135

//This will be true
if ([latestVersion compare:currentVersion options:NSNumericSearch] == NSOrderedDescending) {
     //This will be true
}

**Comment by emotality** [comment]
> > //This will be true

Are you assuming or are you actually experiencing a problem?
Because this was solved in issue #1

**Comment by atrwang** [comment]
not exactly like #1 , [bundleInfo objectForKey:@"CFBundleShortVersionString"] just get short version, not include build number (like 1.4).  the verson returned from apple lookup api  include build bumber (like 1.4.5).

Suggest you join build number.
 NSString _versionStr = [[[NSBundle mainBundle] infoDictionary] objectForKey:@"CFBundleShortVersionString"];
    NSString *buildStr = [[[NSBundle mainBundle] infoDictionary] objectForKey:(NSString *)kCFBundleVersionKey];
    NSString_ currentVersion = [NSString stringWithFormat:@"%@.%@",versionStr,buildStr];

**Comment by emotality** [comment]
It's comparing the versions, not the build. If I do as you say above, it will always be greater than just the version number.

Have to compare apples with apples, not apples with apples + pears. ;)
But please feel free to do this in your own project :yum:
